/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miempresa.proyectoventas.vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author jjqoj
 */
public class VistaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultar
     */
    public VistaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        botonConsultarProducto = new javax.swing.JButton();
        msgError = new javax.swing.JLabel();
        resultadoConsultarCodigo = new javax.swing.JLabel();
        resultadoConsultarNombre = new javax.swing.JLabel();
        resultadoConsultarDescripcion = new javax.swing.JLabel();
        resultadoConsultarPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ancizar Sans", 1, 24)); // NOI18N
        jLabel1.setText("Consulte los registros sobre ventas");

        jLabel2.setFont(new java.awt.Font("Ancizar Sans", 0, 18)); // NOI18N
        jLabel2.setText("Código Producto");

        botonConsultarProducto.setFont(new java.awt.Font("Ancizar Sans", 0, 24)); // NOI18N
        botonConsultarProducto.setText("Consultar");

        msgError.setFont(new java.awt.Font("Ancizar Sans", 0, 18)); // NOI18N
        msgError.setForeground(new java.awt.Color(255, 0, 51));
        msgError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resultadoConsultarCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        resultadoConsultarNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        resultadoConsultarDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        resultadoConsultarPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resultadoConsultarPrecio.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(botonConsultarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(msgError, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoConsultarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoConsultarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoConsultarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(27, 27, 27)
                            .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(botonConsultarProducto)
                .addGap(33, 33, 33)
                .addComponent(resultadoConsultarCodigo)
                .addGap(18, 18, 18)
                .addComponent(resultadoConsultarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultadoConsultarDescripcion)
                .addGap(12, 12, 12)
                .addComponent(resultadoConsultarPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(msgError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarProducto;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel msgError;
    private javax.swing.JLabel resultadoConsultarCodigo;
    private javax.swing.JLabel resultadoConsultarDescripcion;
    private javax.swing.JLabel resultadoConsultarNombre;
    private javax.swing.JLabel resultadoConsultarPrecio;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonConsultarProducto() {
        return botonConsultarProducto;
    }

    public void setBotonConsultarProducto(JButton botonConsultarProducto) {
        this.botonConsultarProducto = botonConsultarProducto;
    }

    public JTextField getCodigoProducto() {
        return codigoProducto;
    }

    public void setCodigoProducto(JTextField codigoProducto) {
        this.codigoProducto = codigoProducto;
    }

    public JLabel getMsgError() {
        return msgError;
    }

    public void setMsgError(JLabel msgError) {
        this.msgError = msgError;
    }

    public JLabel getResultadoConsultarCodigo() {
        return resultadoConsultarCodigo;
    }

    public void setResultadoConsultarCodigo(JLabel resultadoConsultarCodigo) {
        this.resultadoConsultarCodigo = resultadoConsultarCodigo;
    }

    public JLabel getResultadoConsultarDescripcion() {
        return resultadoConsultarDescripcion;
    }

    public void setResultadoConsultarDescripcion(JLabel resultadoConsultarDescripcion) {
        this.resultadoConsultarDescripcion = resultadoConsultarDescripcion;
    }

    public JLabel getResultadoConsultarNombre() {
        return resultadoConsultarNombre;
    }

    public void setResultadoConsultarNombre(JLabel resultadoConsultarNombre) {
        this.resultadoConsultarNombre = resultadoConsultarNombre;
    }

    public JLabel getResultadoConsultarPrecio() {
        return resultadoConsultarPrecio;
    }

    public void setResultadoConsultarPrecio(JLabel resultadoConsultarPrecio) {
        this.resultadoConsultarPrecio = resultadoConsultarPrecio;
    }

    
   



}
